= PJSON Readme
Alexander Olsson <noseglid@gmail.com>

== libpjson
PJSON is a slim, and easy to use JSON interpreter for use in the C++ language.

The API may still change. Only use this for testing purposes until a stable
release is up for downloads. At which point the API will be almost guaranteed.
There will be no changes to the API unless it is *required* for continued
development, and even at this stage it will be thourougly weighed.

== Dependencies
* http://www.gnu.org/software/libtool/[libtool]
* http://www.boost.org/[boost] (only headers required; +variant+ and +lexical_cast+)

If you're on a debian derivative (debian, ubuntu, ..) you can use the following to get
the prerequisites (as root):
----
# apt-get install libtool libboost-all-dev
----

== Install
Installation should be as easy as 1-2-3:

----
# ./configure
# make
# make install
----

Step 3 must be run as root, while step 1 and 2 do not require this.

== Why?
There are several JSON interpreters/parsers out there, why would I go about
creating my own one? Several reasons:

* As an initial project, I did it to learn the basics of +C+++ and the +boost+ library.
* The existing JSON interpreters had flaws I decided I could not accept.
  Among others were loads of valgrind warings, memory leaks and difficult to learn API.
